### ISSUE TITLE
Could you tell me what was I doing wrong

### ISSUE THREAD

**Issue by Amraan-Amjad** [notmarek/libbydl#1]
Heyy @notmarek 
Could you tell me what was I doing wrong
![image](https://github.com/notmarek/libbydl/assets/121578485/60a02f54-3374-43b0-b390-e3e5d2c9252a)
Pardon me
I am a absolute dimwit at Python

**Comment by notmarek** [comment]
You didn't even manage to clone the repo

**Comment by Amraan-Amjad** [comment]
What should I do

**Comment by notmarek** [comment]
> What should I do

start by learning how to download content from github

**Comment by Amraan-Amjad** [comment]
Do you have any sort of guide on how to do so

**Comment by Amraan-Amjad** [comment]
@notmarek 
Could you please help me out here
